twig:
    file_name_pattern: '*.twig'
    form_themes:
        - bootstrap_5_layout.html.twig
    globals:
        site_name: "Les chroniques du code"

when@test:
    twig:
        strict_variables: true
