version: '3.7'
services:
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blogSymfony
    ports:
      - "3307:3306"
    expose:
      - "3306"
