# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/Model/'

    App\Infrastructure\Repository\PostRepositoryInterface:
        alias: App\Infrastructure\Persistence\DoctrinePostRepository

    App\Domain\UseCaseInterface\Post\CreatePostInterface:
        alias: App\Domain\UseCase\Post\CreatePost

    App\Domain\UseCaseInterface\Post\ListAllPostsInterface:
        alias: App\Domain\UseCase\Post\ListAllPosts

    App\Domain\UseCaseInterface\Post\ListPublishedPostsInterface:
        alias: App\Domain\UseCase\Post\ListPublishedPosts

    App\Domain\UseCaseInterface\Post\GetPostInterface:
        alias: App\Domain\UseCase\Post\GetPost

    App\Domain\UseCaseInterface\Post\UpdatePostInterface:
        alias: App\Domain\UseCase\Post\UpdatePost

    App\Domain\UseCaseInterface\Post\DeletePostInterface:
        alias: App\Domain\UseCase\Post\DeletePost

    App\Infrastructure\Repository\UserRepositoryInterface:
        alias: App\Infrastructure\Persistence\DoctrineUserRepository

    App\Domain\UseCaseInterface\RegisterUserInterface:
        alias: App\Domain\UseCase\RegisterUser

    App\Domain\Service\PasswordHasherInterface:
        alias: App\Infrastructure\Security\SymfonyPasswordHasher

    App\Infrastructure\Twig\Component\ShareButtons:
        arguments:
            $sharingServices: !tagged_iterator app.sharing_service

    App\Infrastructure\Twig\Component\Footer:
        arguments:
            $socialLinks: !tagged_iterator app.social_link

    _instanceof:
        App\Domain\Service\Sharing\SharingServiceInterface:
            tags: ['app.sharing_service']
        App\Domain\Service\Social\SocialLinkInterface:
            tags: ['app.social_link']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Infrastructure\Admin\PostAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Infrastructure\Entity\Post, manager_type: orm, group: blog, label: Posts }

    App\Infrastructure\Admin\TagAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Infrastructure\Entity\Tag, manager_type: orm, group: blog, label: Tags }

    App\Infrastructure\Admin\UserAdmin:
        tags:
            - { name: sonata.admin, model_class: App\Infrastructure\Entity\User, manager_type: orm, group: blog, label: Users }
